services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-cli
    container_name: php_web
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - "8100:8080"
    stdin_open: true
    tty: true
