services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    image: php:7.2.2-cli
    container_name: php_cli
    depends_on:
      - mysql
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
